//export const GET_USERS = 'GET_USERS';
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';


export const GET_USERBYID_REQUESTED = 'GET_USERBYID_REQUESTED';
export const GET_USERBYID_SUCCESS = 'GET_USERBYID_SUCCESS';
export const GET_USERBYID_FAILED = 'GET_USERBYID_FAILED';

export const GET_SORTUSERS_REQUESTED = 'GET_SORTUSERS_REQUESTED';
export const GET_SORTUSERS_SUCCESS = 'GET_SORTUSERS_SUCCESS';
export const GET_SORTUSERS_FAILED = 'GET_SORTUSERS_FAILED';


export const ADD_USER_REQUESTED = 'GET_USERS_REQUESTED';
export const ADD_USER_SUCCESS = 'GET_USERS_SUCCESS';
export const ADD_USER_FAILED = 'GET_USERS_FAILED';

export const DELETE_USERBYID_SUCCESS = 'DELETE_USERBYID_SUCCESS';
